name: flutter_xupdate
description: A Flutter plugin for XUpdate(Android Version Update Library).
version: 3.0.1
homepage: https://gitee.com/heIIoworId/flutter_xupdate
repository: https://gitee.com/heIIoworId/flutter_xupdate
issue_tracker: https://gitee.com/heIIoworId/flutter_xupdate/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xuexiang.flutter_xupdate
        pluginClass: FlutterXUpdatePlugin
